//PRODUCTS
export const ADDPRODUCT = 'ADDPRODUCT';
export const UPDATEPRODUCT = 'UPDATEPRODUCT';
export const DELETEPRODUCT = 'DELETEPRODUCT';
export const FETCHPRODUCTS = 'FETCHPRODUCTS';
export const BULKUPLOAD = 'BULKUPLOAD';
//ORDERS
export const CREATEORDER="CREATEORDER";
export const GETUSERORDERS="GETUSERORDERS";
//Auth
export const LOGOUT="LOGOUT"
export const AUTH="AUTH"
export const GOOGLEAUTH="GOOGLEAUTH"
//mobileplans and broadband
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const GET_DATAC = 'GET_DATAC';
export const CREATE_PLAN = 'CREATE_PLAN';
export const GET_PLAN = 'GET_PLAN';
export const GET_BROADBAND_PLAN = 'GET_BROADBAND_PLAN';
export const CREATE_BROADBAND_PLAN = 'CREATE_BROADBAND_PLAN';
export const GET_USERS = 'GET_USERS';
export const DELETE_BROADBAND="DELETE_BROADBAND";
export const UPDATE_BROADBAND_PLAN="UPDATE_BROADBAND_PLAN"
export const GET_CARDS="GET_CARDS";
export const CREATE_CARDS="CREATE_CARDS";
export const GET_BLOCATION = "GET_BLOCATION";
export const PAY_MOBILE = "PAY_MOBILE";
export const PAY_BROADBAND = "PAY_BROADBAND";
export const GET_CURRENT_BROADBAND="GET_CURRENT_BROADBAND";
export const SEARCH="SEARCH";
export const GET_BROADBAND_HIS="GET_BROADBAND_HIS";
export const GET_PLAN_BYID="GET_PLAN_BYID";
export const UPGRADE_BROADBAND="UPGRADE_BROADBAND"
//Search
export const SEARCHPRODUCT="SEARCHPRODUCT"
//cart
export const ADDTOCART="ADDTOCART"
export const UPDATECART="UPDATECART"
export const FETCHCART="FETCHCART"
export const DELETEFROMCART="DELETEFROMCART"
export const EMPTYCART="EMPTYCART"

//likes and reviews
export const LIKE="LIKE"
export const ADDREVIEW="ADDREVIEW"
export const UPDATEREVIEW="UPDATEREVIEW"
export const DELETEREVIEW="DELETEREVIEW"
